// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrfqcoynaouinoktmzpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZnFjb3luYW91aW5va3RtenByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjMyODIsImV4cCI6MjA2ODMzOTI4Mn0.S_FCb5FwlGOPVVo4ERAkpKIflYUUapwhlwP4DPcqK50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});